[general]
url = "https://nuttycream.github.io/sussg/"
output_dir = "public"

[style]
# default styles to use if not otherwise specified in the frontmatter
main = ["main", "fonts"] 

[template]
base = "base" # default template to use if not otherwise specified in the frontmatter
